import type { Profile } from '@/lib/types';

const now = new Date().toISOString();
const ago = (days: number) => new Date(Date.now() - days * 86400000).toISOString();
const future = (days: number) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10);

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'demo-001',
    slug: 'marco-rossi-op001',
    language: 'it',
    status: 'active',
    visibility: 'public',
    verificationStatus: 'verified',
    createdAt: ago(90),
    updatedAt: ago(2),
    publishedAt: ago(85),
    lastVerifiedAt: ago(10),
    person: {
      firstName: 'Marco',
      lastName: 'Rossi',
      birthDate: '1985-03-12',
      nationality: 'Italian',
      operatorCode: 'OP-2024-001',
      operatorLicense: 'IT-RPL-A2-2024-4521',
      emergencyContact: '+39 333 9876543',
    },
    organization: {
      companyName: 'Alpine Drones SRL',
      companyDetails: 'Professional aerial survey and inspection services.\nSpecializing in mountain and alpine environments.',
      companyAddress: 'Via Roma 42, 39100 Bolzano (BZ), Italy',
      companyVatOrRegistration: 'IT02345678901 / REA BZ-123456',
    },
    drone: {
      droneName: 'Summit Scout',
      droneModel: 'DJI Matrice 350 RTK',
      droneSerialNumber: '1ZNBJ4M0030A7E',
      droneRegistrationCode: 'IT-UAS-042-2024',
    },
    insurance: {
      provider: 'Allianz Aviation Insurance',
      policyNumber: 'AV-2024-78901-IT',
      issueDate: '2024-01-15',
      expiryDate: future(240),
      notes: 'Covers VLOS and BVLOS operations within EU airspace.',
      pdfUrl: '',
    },
    assets: {
      profilePhotoUrl: '',
      logoUrl: '',
      bannerUrl: '',
      qrCodeUrl: '',
      nfcReference: '',
    },
    documents: [],
    admin: {
      internalNotes: 'Demo profile — verified operator.',
      lastEditedBy: 'admin@dronetag.io',
    },
  },
  {
    id: 'demo-002',
    slug: 'anna-mueller-op002',
    language: 'de',
    status: 'active',
    visibility: 'public',
    verificationStatus: 'pending',
    createdAt: ago(45),
    updatedAt: ago(1),
    publishedAt: ago(40),
    lastVerifiedAt: '',
    person: {
      firstName: 'Anna',
      lastName: 'Müller',
      birthDate: '1992-07-22',
      nationality: 'German',
      operatorCode: 'OP-2024-002',
      operatorLicense: 'DE-A2-2024-8834',
      emergencyContact: '+49 170 1234567',
    },
    organization: {
      companyName: 'SkyMap GmbH',
      companyDetails: 'Urban mapping and infrastructure inspection.',
      companyAddress: 'Hauptstr. 15, 80331 München, Germany',
      companyVatOrRegistration: 'DE298765432',
    },
    drone: {
      droneName: 'CityMapper',
      droneModel: 'Autel EVO II Pro',
      droneSerialNumber: 'AU7K22B003421',
      droneRegistrationCode: 'DE-UAS-091-2024',
    },
    insurance: {
      provider: 'HDI Versicherung',
      policyNumber: 'HDI-UAS-2024-553',
      issueDate: '2024-03-01',
      expiryDate: future(18),
      notes: 'Expiring soon — renewal pending.',
      pdfUrl: '',
    },
    assets: {
      profilePhotoUrl: '',
      logoUrl: '',
      bannerUrl: '',
      qrCodeUrl: '',
      nfcReference: '',
    },
    documents: [],
    admin: {
      internalNotes: 'Insurance renewal in progress.',
      lastEditedBy: 'admin@dronetag.io',
    },
  },
  {
    id: 'demo-003',
    slug: 'pierre-dupont-op003',
    language: 'fr',
    status: 'active',
    visibility: 'private',
    verificationStatus: 'unverified',
    createdAt: ago(10),
    updatedAt: now,
    publishedAt: '',
    lastVerifiedAt: '',
    person: {
      firstName: 'Pierre',
      lastName: 'Dupont',
      birthDate: '',
      nationality: 'French',
      operatorCode: 'OP-2024-003',
      operatorLicense: '',
      emergencyContact: '',
    },
    organization: {
      companyName: 'AeroPro SARL',
      companyDetails: 'Agriculture and precision farming aerial services.',
      companyAddress: '',
      companyVatOrRegistration: '',
    },
    drone: {
      droneName: '',
      droneModel: 'DJI Agras T40',
      droneSerialNumber: '',
      droneRegistrationCode: '',
    },
    insurance: {
      provider: '',
      policyNumber: '',
      issueDate: '',
      expiryDate: '',
      notes: '',
      pdfUrl: '',
    },
    assets: {
      profilePhotoUrl: '',
      logoUrl: '',
      bannerUrl: '',
      qrCodeUrl: '',
      nfcReference: '',
    },
    documents: [],
    admin: {
      internalNotes: 'Incomplete profile — awaiting documentation.',
      lastEditedBy: 'admin@dronetag.io',
    },
  },
  {
    id: 'demo-004',
    slug: 'carlos-garcia-op004',
    language: 'es',
    status: 'active',
    visibility: 'public',
    verificationStatus: 'verified',
    createdAt: ago(120),
    updatedAt: ago(60),
    publishedAt: ago(115),
    lastVerifiedAt: ago(55),
    person: {
      firstName: 'Carlos',
      lastName: 'García',
      birthDate: '1978-11-05',
      nationality: 'Spanish',
      operatorCode: 'OP-2024-004',
      operatorLicense: 'ES-STS-2023-7712',
      emergencyContact: '+34 612 345 678',
    },
    organization: {
      companyName: 'DroneVista S.L.',
      companyDetails: 'Audiovisual production and real estate photography.',
      companyAddress: 'Calle Gran Vía 28, 28013 Madrid, Spain',
      companyVatOrRegistration: 'ESB12345678',
    },
    drone: {
      droneName: 'VistaOne',
      droneModel: 'DJI Inspire 3',
      droneSerialNumber: 'INS3A1002Z9',
      droneRegistrationCode: 'ES-UAS-201-2023',
    },
    insurance: {
      provider: 'Mapfre Seguros',
      policyNumber: 'MPF-UAS-2023-1120',
      issueDate: '2023-06-01',
      expiryDate: ago(15).slice(0, 10),
      notes: 'EXPIRED — operator notified.',
      pdfUrl: '',
    },
    assets: {
      profilePhotoUrl: '',
      logoUrl: '',
      bannerUrl: '',
      qrCodeUrl: '',
      nfcReference: '',
    },
    documents: [],
    admin: {
      internalNotes: 'Insurance expired. Contact operator for renewal.',
      lastEditedBy: 'admin@dronetag.io',
    },
  },
];
